MODEL_PATH = './vectorizing_model/model.bin'
PROFILES_PATH = './profiles/origin_data.json'
DB_PATH = './database/database.sqlite'
VECTORS_PROFILES_PATH = './vectorizing_model/vectors_profiles.bin'
PROFILES_VECTORS_PATH = './vectorizing_model/profiles_vectors.bin'
